In [2]:
import pandas as pd

df = pd.read_csv("/Users/huss/Downloads/shelter_final.csv.csv")

df

,animal_id,name,outcome_type,outcome_subtype,animal_type,sex_upon_outcome,age_upon_outcome,breed,color,monthyear,datetime,date_of_birth
0,A705049,*Fancy,Transfer,Partner,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Black,07-2015,2015-07-02T00:00:00-05:00,2015-04-05
1,A729515,Oreo,Transfer,Partner,Cat,Neutered Male,12 years,Domestic Shorthair Mix,Black/White,06-2016,2016-06-20T00:00:00-05:00,2004-06-19
2,A680862,NaN,Transfer,Partner,Bird,Unknown,2 weeks,Duck,Yellow/Black,06-2014,2014-06-10T00:00:00-05:00,2014-05-25
3,A714876,*Newton,Transfer,Partner,Cat,Neutered Male,3 years,Domestic Shorthair Mix,Orange Tabby/White,11-2015,2015-11-11T00:00:00-05:00,2012-10-29
4,A706507,NaN,Died,In Kennel,Cat,Unknown,5 days,Domestic Shorthair Mix,Black,06-2015,2015-06-30T00:00:00-05:00,2015-06-25
...,...,...,...,...,...,...,...,...,...,...,...,...
173770,A926373,*Owl,Adoption,Foster,Cat,Spayed Female,1 month,Domestic Shorthair,Black,05-2025,2025-05-04 12:48:00,2025-03-09
173771,A926862,*Lagatha,Adoption,NaN,Dog,Intact Female,2 months,German Shepherd Mix,Black/Brown,05-2025,2025-05-01 16:54:00,2025-02-15
173772,A917477,Canelo,Adoption,NaN,Dog,Neutered Male,1 year,Mastiff/Pit Bull,Brown Brindle,05-2025,2025-05-04 17:53:00,2023-11-06
173773,A621834,Nahtha,Adoption,NaN,Dog,Spayed Female,15 years,Jack Russell Terrier Mix,White/Gray,05-2025,2025-05-04 14:18:00,2010-04-24
173774,A929559,NaN,Transfer,Partner,Cat,Intact Male,1 month,Domestic Shorthair,Gray Tabby/White,05-2025,2025-05-05 0:00:00,2025-03-19

In [3]:
#nan remove and see what you want to do with that
# Drop columns which we wont use 

df = df.drop(columns=["name","sex_upon_outcome","outcome_subtype","monthyear"])
df

,animal_id,outcome_type,animal_type,age_upon_outcome,breed,color,datetime,date_of_birth
0,A705049,Transfer,Cat,2 months,Domestic Shorthair Mix,Black,2015-07-02T00:00:00-05:00,2015-04-05
1,A729515,Transfer,Cat,12 years,Domestic Shorthair Mix,Black/White,2016-06-20T00:00:00-05:00,2004-06-19
2,A680862,Transfer,Bird,2 weeks,Duck,Yellow/Black,2014-06-10T00:00:00-05:00,2014-05-25
3,A714876,Transfer,Cat,3 years,Domestic Shorthair Mix,Orange Tabby/White,2015-11-11T00:00:00-05:00,2012-10-29
4,A706507,Died,Cat,5 days,Domestic Shorthair Mix,Black,2015-06-30T00:00:00-05:00,2015-06-25
...,...,...,...,...,...,...,...,...
173770,A926373,Adoption,Cat,1 month,Domestic Shorthair,Black,2025-05-04 12:48:00,2025-03-09
173771,A926862,Adoption,Dog,2 months,German Shepherd Mix,Black/Brown,2025-05-01 16:54:00,2025-02-15
173772,A917477,Adoption,Dog,1 year,Mastiff/Pit Bull,Brown Brindle,2025-05-04 17:53:00,2023-11-06
173773,A621834,Adoption,Dog,15 years,Jack Russell Terrier Mix,White/Gray,2025-05-04 14:18:00,2010-04-24
173774,A929559,Transfer,Cat,1 month,Domestic Shorthair,Gray Tabby/White,2025-05-05 0:00:00,2025-03-19

In [4]:


df2=df.dropna()

df2

,animal_id,outcome_type,animal_type,age_upon_outcome,breed,color,datetime,date_of_birth
0,A705049,Transfer,Cat,2 months,Domestic Shorthair Mix,Black,2015-07-02T00:00:00-05:00,2015-04-05
1,A729515,Transfer,Cat,12 years,Domestic Shorthair Mix,Black/White,2016-06-20T00:00:00-05:00,2004-06-19
2,A680862,Transfer,Bird,2 weeks,Duck,Yellow/Black,2014-06-10T00:00:00-05:00,2014-05-25
3,A714876,Transfer,Cat,3 years,Domestic Shorthair Mix,Orange Tabby/White,2015-11-11T00:00:00-05:00,2012-10-29
4,A706507,Died,Cat,5 days,Domestic Shorthair Mix,Black,2015-06-30T00:00:00-05:00,2015-06-25
...,...,...,...,...,...,...,...,...
173770,A926373,Adoption,Cat,1 month,Domestic Shorthair,Black,2025-05-04 12:48:00,2025-03-09
173771,A926862,Adoption,Dog,2 months,German Shepherd Mix,Black/Brown,2025-05-01 16:54:00,2025-02-15
173772,A917477,Adoption,Dog,1 year,Mastiff/Pit Bull,Brown Brindle,2025-05-04 17:53:00,2023-11-06
173773,A621834,Adoption,Dog,15 years,Jack Russell Terrier Mix,White/Gray,2025-05-04 14:18:00,2010-04-24
173774,A929559,Transfer,Cat,1 month,Domestic Shorthair,Gray Tabby/White,2025-05-05 0:00:00,2025-03-19

In [19]:
df2["age_upon_outcome"].isna().sum()
df2["outcome_type"].isna().sum()
df2.reset_index (drop=True, inplace =True)

In [20]:
display(df2)

,animal_id,outcome_type,animal_type,age_upon_outcome,breed,color,datetime,date_of_birth
0,A705049,Transfer,Cat,2 months,Domestic Shorthair Mix,Black,2015-07-02T00:00:00-05:00,2015-04-05
1,A729515,Transfer,Cat,12 years,Domestic Shorthair Mix,Black/White,2016-06-20T00:00:00-05:00,2004-06-19
2,A680862,Transfer,Bird,2 weeks,Duck,Yellow/Black,2014-06-10T00:00:00-05:00,2014-05-25
3,A714876,Transfer,Cat,3 years,Domestic Shorthair Mix,Orange Tabby/White,2015-11-11T00:00:00-05:00,2012-10-29
4,A706507,Died,Cat,5 days,Domestic Shorthair Mix,Black,2015-06-30T00:00:00-05:00,2015-06-25
...,...,...,...,...,...,...,...,...
173715,A926373,Adoption,Cat,1 month,Domestic Shorthair,Black,2025-05-04 12:48:00,2025-03-09
173716,A926862,Adoption,Dog,2 months,German Shepherd Mix,Black/Brown,2025-05-01 16:54:00,2025-02-15
173717,A917477,Adoption,Dog,1 year,Mastiff/Pit Bull,Brown Brindle,2025-05-04 17:53:00,2023-11-06
173718,A621834,Adoption,Dog,15 years,Jack Russell Terrier Mix,White/Gray,2025-05-04 14:18:00,2010-04-24
173719,A929559,Transfer,Cat,1 month,Domestic Shorthair,Gray Tabby/White,2025-05-05 0:00:00,2025-03-19

In [21]:
df2.to_csv("clean_shelter_file", index=False)